let s1='hello';
console.log(s1);
let s2='owu';
console.log(s2);
let s3='com';
console.log(s3);
let s4='ua';
console.log(s4);
let n1= 1;
console.log(n1);
let n2= 10;
console.log(n2);
let n3= -999;
console.log(n3);
let n4= 123;
console.log(n4);
let n5= 3.14;
console.log(n5);
let n6= 2.7;
console.log(n6);
let n7= 16;
console.log(n7);
let b1= n1 < n2;
console.log(b1);
let b2= n1 > n2;
console.log(b2);
let lastName='Салій ';
let firstName='Любов ';
let middleName='Петрівна';
console.log(lastName+firstName+middleName);
let a = 100;
let b = '100';
let c = true;
console.log(typeof a, b, c);